openapi: '3.0.0'

info:
  title: B-Mail API Backend
  description: B-Mail API Backend
  contact:
    email: bmlopez024@gmail.com
  license:
    name: MIT
    url: https://github.com/blopez024/b-mail/blob/main/LICENSE.md
  version: 1.0.0

servers:
  - url: http://localhost:3010/v0

tags:
  - name: mail
    description: Operations about mail
    externalDocs:
      description: Find out more
      url: https://swagger.io/specification/

paths:
  /mail:
    get:
      tags:
        - mail
      parameters:
        - name: mailbox
          in: query
          required: false
          schema:
            type: string
            pattern: '[A-Za-z]'
      description: Returns all EMail
      responses:
        200:
          description: EMail Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MailBoxes'
        404:
          description: Mailbox with the specified name was not found.
        500:
          description: Internal Server Error

    post:
      tags:
        - mail
      description: Creates a new mail
      requestBody:
        description: EMail to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMail'
      responses:
        201:
          description: Application response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mail'
        400:
          description: Unexpected properties.
        500:
          description: Internal Server Error

  /mail/{id}:
    get:
      tags:
        - mail
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: '\b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b'
      description: Return EMail with the given id
      responses:
        200:
          description: EMail Response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mail'
        404:
          description: EMail with the specified id was not found.
        500:
          description: Internal Server Error

    put:
      tags:
        - mail
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: '\b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b'
        - name: mailbox
          in: query
          required: true
          schema:
            type: string
            pattern: '[A-Za-z]'
      description: Moves email with the specified id to the specified mailbox.
      responses:
        204:
          description: Fullfilled request.
        404:
          description: EMail with the specified id was not found.
        409:
          description: Email not in sent mailbox.
        500:
          description: Internal Server Error

components:
  schemas:
    MailInfo:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the email
        from-name:
          type: string
          description: Name of the sender
        from-email:
          type: string
          description: Email address of the sender
        to-name:
          type: string
          description: Name of the recipient
        to-email:
          type: string
          description: Email address of the recipient
        subject:
          type: string
          description: Subject of the email
        sent:
          type: string
          description: Sent timestamp
        received:
          type: string
          description: Received timestamp
      required:
        - id
        - from-name
        - from-email
        - to-name
        - to-email
        - subject
        - sent
        - received

    Mail:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the email
        from-name:
          type: string
          description: Name of the sender
        from-email:
          type: string
          description: Email address of the sender
        to-name:
          type: string
          description: Name of the recipient
        to-email:
          type: string
          description: Email address of the recipient
        subject:
          type: string
          description: Subject of the email
        sent:
          type: string
          description: Sent timestamp
        received:
          type: string
          description: Received timestamp
        content:
          type: string
          description: Content of the email
      required:
        - id
        - from-name
        - from-email
        - to-name
        - to-email
        - subject
        - sent
        - received
        # - content

    MailBox:
      type: object
      properties:
        name:
          type: string
          description: Name of the mailbox
        mail:
          type: array
          items:
            $ref: '#/components/schemas/Mail'
      required:
        - name
        - mail

    MailBoxes:
      type: array
      items:
        $ref: '#/components/schemas/MailBox'

    NewMail:
      type: object
      properties:
        to:
          type: object
          properties:
            name:
              type: string
              description: Name of the recipient
            email:
              type: string
              description: Email address of the recipient
          required:
            - name
            - email
        subject:
          type: string
          description: Subject of the email
        content:
          type: string
          description: Content of the email
      required:
        - to
        - subject
        - content

    # Email:
    #   type: object
    #   properties:
    #     recipient:
    #       $ref: '#/components/schemas/Person'
    #     sender:
    #       $ref: '#/components/schemas/Person'
