name: PNPM Lint

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  pnpm-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Increased the timeout to account for both frontend and backend installs
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.0'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml' # Cache based on the lockfile for better cache hits

      # - name: Install dependencies for frontend
      #   run: |
      #     cd frontend
      #     pnpm install

      - name: Install dependencies for backend
        run: |
          cd backend
          pnpm install

      - name: Verify pnpm installation
        run: pnpm --version

      # - name: Run linter for frontend
      #   run: |
      #     cd frontend
      #     pnpm run lint

      - name: Run linter for backend
        run: |
          cd backend
          pnpm run lint
